//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentsSpec) DeepCopyInto(out *AgentsSpec) {
	*out = *in
	out.Coverage = in.Coverage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentsSpec.
func (in *AgentsSpec) DeepCopy() *AgentsSpec {
	if in == nil {
		return nil
	}
	out := new(AgentsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CampaignDashboardSpec) DeepCopyInto(out *CampaignDashboardSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CampaignDashboardSpec.
func (in *CampaignDashboardSpec) DeepCopy() *CampaignDashboardSpec {
	if in == nil {
		return nil
	}
	out := new(CampaignDashboardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CampaignDriverSpec) DeepCopyInto(out *CampaignDriverSpec) {
	*out = *in
	out.Invariants = in.Invariants
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CampaignDriverSpec.
func (in *CampaignDriverSpec) DeepCopy() *CampaignDriverSpec {
	if in == nil {
		return nil
	}
	out := new(CampaignDriverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClosureJVMCampaign) DeepCopyInto(out *ClosureJVMCampaign) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClosureJVMCampaign.
func (in *ClosureJVMCampaign) DeepCopy() *ClosureJVMCampaign {
	if in == nil {
		return nil
	}
	out := new(ClosureJVMCampaign)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClosureJVMCampaign) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClosureJVMCampaignList) DeepCopyInto(out *ClosureJVMCampaignList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClosureJVMCampaign, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClosureJVMCampaignList.
func (in *ClosureJVMCampaignList) DeepCopy() *ClosureJVMCampaignList {
	if in == nil {
		return nil
	}
	out := new(ClosureJVMCampaignList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClosureJVMCampaignList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClosureJVMCampaignSpec) DeepCopyInto(out *ClosureJVMCampaignSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	out.Driver = in.Driver
	out.Dashboard = in.Dashboard
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClosureJVMCampaignSpec.
func (in *ClosureJVMCampaignSpec) DeepCopy() *ClosureJVMCampaignSpec {
	if in == nil {
		return nil
	}
	out := new(ClosureJVMCampaignSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClosureJVMCampaignStatus) DeepCopyInto(out *ClosureJVMCampaignStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClosureJVMCampaignStatus.
func (in *ClosureJVMCampaignStatus) DeepCopy() *ClosureJVMCampaignStatus {
	if in == nil {
		return nil
	}
	out := new(ClosureJVMCampaignStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClosureJVMTarget) DeepCopyInto(out *ClosureJVMTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClosureJVMTarget.
func (in *ClosureJVMTarget) DeepCopy() *ClosureJVMTarget {
	if in == nil {
		return nil
	}
	out := new(ClosureJVMTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClosureJVMTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClosureJVMTargetList) DeepCopyInto(out *ClosureJVMTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClosureJVMTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClosureJVMTargetList.
func (in *ClosureJVMTargetList) DeepCopy() *ClosureJVMTargetList {
	if in == nil {
		return nil
	}
	out := new(ClosureJVMTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClosureJVMTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClosureJVMTargetSpec) DeepCopyInto(out *ClosureJVMTargetSpec) {
	*out = *in
	out.DeploymentRef = in.DeploymentRef
	out.Agents = in.Agents
	out.Invariants = in.Invariants
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClosureJVMTargetSpec.
func (in *ClosureJVMTargetSpec) DeepCopy() *ClosureJVMTargetSpec {
	if in == nil {
		return nil
	}
	out := new(ClosureJVMTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClosureJVMTargetStatus) DeepCopyInto(out *ClosureJVMTargetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClosureJVMTargetStatus.
func (in *ClosureJVMTargetStatus) DeepCopy() *ClosureJVMTargetStatus {
	if in == nil {
		return nil
	}
	out := new(ClosureJVMTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoverageSpec) DeepCopyInto(out *CoverageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoverageSpec.
func (in *CoverageSpec) DeepCopy() *CoverageSpec {
	if in == nil {
		return nil
	}
	out := new(CoverageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentReference) DeepCopyInto(out *DeploymentReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentReference.
func (in *DeploymentReference) DeepCopy() *DeploymentReference {
	if in == nil {
		return nil
	}
	out := new(DeploymentReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvariantsSpec) DeepCopyInto(out *InvariantsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvariantsSpec.
func (in *InvariantsSpec) DeepCopy() *InvariantsSpec {
	if in == nil {
		return nil
	}
	out := new(InvariantsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetReference) DeepCopyInto(out *TargetReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetReference.
func (in *TargetReference) DeepCopy() *TargetReference {
	if in == nil {
		return nil
	}
	out := new(TargetReference)
	in.DeepCopyInto(out)
	return out
}
