//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentsSpec) DeepCopyInto(out *AgentsSpec) {
	*out = *in
	if in.ThreadTracker != nil {
		in, out := &in.ThreadTracker, &out.ThreadTracker
		*out = new(bool)
		**out = **in
	}
	out.Coverage = in.Coverage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentsSpec.
func (in *AgentsSpec) DeepCopy() *AgentsSpec {
	if in == nil {
		return nil
	}
	out := new(AgentsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasquinCampaign) DeepCopyInto(out *BasquinCampaign) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasquinCampaign.
func (in *BasquinCampaign) DeepCopy() *BasquinCampaign {
	if in == nil {
		return nil
	}
	out := new(BasquinCampaign)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BasquinCampaign) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasquinCampaignList) DeepCopyInto(out *BasquinCampaignList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BasquinCampaign, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasquinCampaignList.
func (in *BasquinCampaignList) DeepCopy() *BasquinCampaignList {
	if in == nil {
		return nil
	}
	out := new(BasquinCampaignList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BasquinCampaignList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasquinCampaignSpec) DeepCopyInto(out *BasquinCampaignSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	out.Driver = in.Driver
	in.Dashboard.DeepCopyInto(&out.Dashboard)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasquinCampaignSpec.
func (in *BasquinCampaignSpec) DeepCopy() *BasquinCampaignSpec {
	if in == nil {
		return nil
	}
	out := new(BasquinCampaignSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasquinCampaignStatus) DeepCopyInto(out *BasquinCampaignStatus) {
	*out = *in
	if in.Load != nil {
		in, out := &in.Load, &out.Load
		*out = new(LoadStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasquinCampaignStatus.
func (in *BasquinCampaignStatus) DeepCopy() *BasquinCampaignStatus {
	if in == nil {
		return nil
	}
	out := new(BasquinCampaignStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasquinTarget) DeepCopyInto(out *BasquinTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasquinTarget.
func (in *BasquinTarget) DeepCopy() *BasquinTarget {
	if in == nil {
		return nil
	}
	out := new(BasquinTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BasquinTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasquinTargetList) DeepCopyInto(out *BasquinTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BasquinTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasquinTargetList.
func (in *BasquinTargetList) DeepCopy() *BasquinTargetList {
	if in == nil {
		return nil
	}
	out := new(BasquinTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BasquinTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasquinTargetSpec) DeepCopyInto(out *BasquinTargetSpec) {
	*out = *in
	out.DeploymentRef = in.DeploymentRef
	in.Agents.DeepCopyInto(&out.Agents)
	out.Invariants = in.Invariants
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasquinTargetSpec.
func (in *BasquinTargetSpec) DeepCopy() *BasquinTargetSpec {
	if in == nil {
		return nil
	}
	out := new(BasquinTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasquinTargetStatus) DeepCopyInto(out *BasquinTargetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasquinTargetStatus.
func (in *BasquinTargetStatus) DeepCopy() *BasquinTargetStatus {
	if in == nil {
		return nil
	}
	out := new(BasquinTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CampaignDashboardSpec) DeepCopyInto(out *CampaignDashboardSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CampaignDashboardSpec.
func (in *CampaignDashboardSpec) DeepCopy() *CampaignDashboardSpec {
	if in == nil {
		return nil
	}
	out := new(CampaignDashboardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CampaignDriverSpec) DeepCopyInto(out *CampaignDriverSpec) {
	*out = *in
	out.Invariants = in.Invariants
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CampaignDriverSpec.
func (in *CampaignDriverSpec) DeepCopy() *CampaignDriverSpec {
	if in == nil {
		return nil
	}
	out := new(CampaignDriverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoverageSpec) DeepCopyInto(out *CoverageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoverageSpec.
func (in *CoverageSpec) DeepCopy() *CoverageSpec {
	if in == nil {
		return nil
	}
	out := new(CoverageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentReference) DeepCopyInto(out *DeploymentReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentReference.
func (in *DeploymentReference) DeepCopy() *DeploymentReference {
	if in == nil {
		return nil
	}
	out := new(DeploymentReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvariantsSpec) DeepCopyInto(out *InvariantsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvariantsSpec.
func (in *InvariantsSpec) DeepCopy() *InvariantsSpec {
	if in == nil {
		return nil
	}
	out := new(InvariantsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadLatency) DeepCopyInto(out *LoadLatency) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadLatency.
func (in *LoadLatency) DeepCopy() *LoadLatency {
	if in == nil {
		return nil
	}
	out := new(LoadLatency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadStatus) DeepCopyInto(out *LoadStatus) {
	*out = *in
	out.LatencyMs = in.LatencyMs
	if in.HeapDriftKb != nil {
		in, out := &in.HeapDriftKb, &out.HeapDriftKb
		*out = new(int64)
		**out = **in
	}
	if in.ThreadDrift != nil {
		in, out := &in.ThreadDrift, &out.ThreadDrift
		*out = new(int32)
		**out = **in
	}
	in.Violations.DeepCopyInto(&out.Violations)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadStatus.
func (in *LoadStatus) DeepCopy() *LoadStatus {
	if in == nil {
		return nil
	}
	out := new(LoadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadViolations) DeepCopyInto(out *LoadViolations) {
	*out = *in
	if in.Latency != nil {
		in, out := &in.Latency, &out.Latency
		*out = new(int32)
		**out = **in
	}
	if in.Heap != nil {
		in, out := &in.Heap, &out.Heap
		*out = new(int32)
		**out = **in
	}
	if in.Thread != nil {
		in, out := &in.Thread, &out.Thread
		*out = new(int32)
		**out = **in
	}
	if in.NotEvaluated != nil {
		in, out := &in.NotEvaluated, &out.NotEvaluated
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadViolations.
func (in *LoadViolations) DeepCopy() *LoadViolations {
	if in == nil {
		return nil
	}
	out := new(LoadViolations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetReference) DeepCopyInto(out *TargetReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetReference.
func (in *TargetReference) DeepCopy() *TargetReference {
	if in == nil {
		return nil
	}
	out := new(TargetReference)
	in.DeepCopyInto(out)
	return out
}
