---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - basquin.dev
  resources:
  - basquincampaigns
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - basquin.dev
  resources:
  - basquincampaigns/finalizers
  verbs:
  - update
- apiGroups:
  - basquin.dev
  resources:
  - basquincampaigns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - basquin.dev
  resources:
  - basquintargets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - basquin.dev
  resources:
  - basquintargets/finalizers
  verbs:
  - update
- apiGroups:
  - basquin.dev
  resources:
  - basquintargets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
