---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - closurejvm.dev
  resources:
  - closurejvmcampaigns
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - closurejvm.dev
  resources:
  - closurejvmcampaigns/finalizers
  verbs:
  - update
- apiGroups:
  - closurejvm.dev
  resources:
  - closurejvmcampaigns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - closurejvm.dev
  resources:
  - closurejvmtargets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - closurejvm.dev
  resources:
  - closurejvmtargets/finalizers
  verbs:
  - update
- apiGroups:
  - closurejvm.dev
  resources:
  - closurejvmtargets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
