apiVersion: closurejvm.dev/v1alpha1
kind: ClosureJVMCampaign
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: closurejvmcampaign-sample
spec:
  # TODO(user): Add fields here
