package com.basquin.maven;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/**
 * The injector's own version, read from a resource Gradle writes from {@code project.version}.
 *
 * <p>Deliberately not a string literal in Java source. The version appears in three places that must
 * agree — this module's {@code version}, the coordinate injected into target builds, and the Pages
 * repository layout — and a literal drifts from the build file the first time one is bumped without
 * the other. The symptom would surface as an unresolvable dependency in somebody else's build.
 */
final class InjectorVersion {

    private static final String RESOURCE = "/basquin-injector.properties";

    private InjectorVersion() {
    }

    static String value() {
        try (InputStream in = InjectorVersion.class.getResourceAsStream(RESOURCE)) {
            if (in == null) {
                throw new IllegalStateException(RESOURCE + " is missing from the injector jar; "
                        + "it is generated by the writeVersionResource Gradle task");
            }
            Properties p = new Properties();
            p.load(in);
            String v = p.getProperty("version");
            if (v == null || v.isBlank()) {
                throw new IllegalStateException(RESOURCE + " has no 'version' property");
            }
            return v;
        } catch (IOException e) {
            throw new IllegalStateException("could not read " + RESOURCE, e);
        }
    }
}
