package com.basquin.maven;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/**
 * The JaCoCo version that Task 2's injected {@code jacoco-maven-plugin:instrument} execution will
 * pin to, read from a resource Gradle writes from the shared root {@code jacocoVersion} property
 * (gradle.properties) — the SAME property the runner's {@code org.jacoco.core} dependency and the
 * {@code jacocoAgent} Tomcat-agent-jar configuration consume (root {@code build.gradle}).
 *
 * <p>Deliberately not a string literal in Java source, for the same reason {@link InjectorVersion}
 * is not: offline-instrumented classes reference the version-specific shaded package
 * {@code org.jacoco.agent.rt.internal_<hash>}, so a hand-typed constant that drifted from the
 * runtime agent's version would silently break the coverage read rather than fail to compile or
 * resolve. {@code JacocoVersionLockstepTest} additionally checks this value against the checked-in
 * gradle.properties text directly, so a stale generated resource or a literal slipped into the
 * resource-writing task would both show up as a test failure rather than a silent skew.
 */
final class JacocoVersion {

    private static final String RESOURCE = "/basquin-injector-jacoco.properties";

    private JacocoVersion() {
    }

    static String value() {
        try (InputStream in = JacocoVersion.class.getResourceAsStream(RESOURCE)) {
            if (in == null) {
                throw new IllegalStateException(RESOURCE + " is missing from the injector jar; "
                        + "it is generated by the writeJacocoVersionResource Gradle task");
            }
            Properties p = new Properties();
            p.load(in);
            String v = p.getProperty("version");
            if (v == null || v.isBlank()) {
                throw new IllegalStateException(RESOURCE + " has no 'version' property");
            }
            return v;
        } catch (IOException e) {
            throw new IllegalStateException("could not read " + RESOURCE, e);
        }
    }
}
